---
title: "Case Study"
author: "Mukta Patwari"
date: "2025-10-07"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Importing data

```{r}
data(nyc_airbnb)
```

Data exploration

```{r}
nyc_airbnb %>%
  drop_na(price) %>% 
  group_by(room_type, neighbourhood_group) %>% 
  summarize( 
  mean_price = mean(price),
  ) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )

top10price = nyc_airbnb %>% 
  arrange(desc(price)) %>% 
  head(10)

highest_reviews = nyc_airbnb %>%
  mutate(
    true_score = review_scores_location/2
  ) %>% 
  arrange(desc(true_score)) %>% 
  head(10)
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood_group, room_type)
```


Making plots

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = price)) +
  geom_histogram() +
  scale_x_continuous(limits = c(0, 1000))
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan",
         price < 500,
         room_type =="Entire home/apt") %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_violin() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

(Remember to look at extreme values...)

```{r}
nyc_airbnb %>% 
  filter(price > 9000)
```

```{r}
nyc_airbnb %>% 
  filter(calculated_host_listings_count > 30)
```

More plots

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan",
         price < 500,
         room_type =="Entire home/apt") %>%
  ggplot(aes(x = lat, y = long, color = review_scores_location)) +
  geom_point()
```

can we make a better map
```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan",
         price < 1000,
         room_type =="Entire home/apt") %>%
  sample_n(25) %>% 
  leaflet() %>% 
  addTiles () %>% 
  addMarkers (~lat, ~long)
```

